[package]
name = "tui-image"
version = "0.1.0"
edition = "2021"
authors = [ "Jessica Rogers" ]
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.5"
tui = "0.19.0"
